name: update-protobuf

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      envoy_version:
        description: 'Envoy version to update to'
        required: true
        type: string

jobs:
  update-protobuf:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
      - name: Run scripts
        working-directory: ./tools/
        run: |
          ./update-sha.sh ${{ inputs.envoy_version }} | tee API_SHAS
          ./update-api.sh
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@6cd32fd93684475c31847837f87bb135d40a2b79  # v7.0.3
        with:
          branch: update-protobuf-to-${{ inputs.envoy_version }}
          base: main
          author: envoy-bot <envoy-bot@users.noreply.github.com>
          committer: envoy-bot <envoy-bot@users.noreply.github.com>
          signoff: true
          title: '[protobuf] Update protobuf definitions to ${{ inputs.envoy_version }}'
          commit-message: |
            [protobuf] Update protobuf definitions to ${{ inputs.envoy_version }}
          body: |
            This is an automatic PR created by github action workflow:
            - Updated protobuf files
