name: update-protobuf

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      envoy_version:
        description: 'Envoy version to update to'
        required: true
        type: string

jobs:
  update-protobuf:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: Run scripts
        working-directory: ./tools/
        run: |
          ./update-sha.sh ${{ inputs.envoy_version }} | tee API_SHAS
          ./update-api.sh
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e  # v7.0.8
        with:
          branch: update-protobuf-to-${{ inputs.envoy_version }}
          base: main
          author: envoy-bot <envoy-bot@users.noreply.github.com>
          committer: envoy-bot <envoy-bot@users.noreply.github.com>
          signoff: true
          title: '[protobuf] Update protobuf definitions to ${{ inputs.envoy_version }}'
          commit-message: |
            [protobuf] Update protobuf definitions to ${{ inputs.envoy_version }}
          body: |
            This is an automatic PR created by github action workflow:
            - Updated protobuf files
